# Generated by Django 4.2.15 on 2025-09-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauths', '__first__'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level', models.CharField(choices=[('tronc commun', 'Tronc Commun'), ('premier bac', 'Premier Bac'), ('deuxieme bac', 'Deuxième Bac')], help_text="Niveau scolaire de l'étudiant", max_length=50)),
                ('points', models.PositiveIntegerField(default=0)),
                ('parent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parents.parent')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('userauths.user',),
        ),
    ]
