# Generated by Django 5.1.7 on 2025-08-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_level',
        ),
    ]
