# Generated by Django 4.2.15 on 2025-09-19 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('summary', models.TextField(blank=True, help_text='Résumé intelligent de la conversation passée.', null=True)),
                ('recent_messages', models.JSONField(blank=True, default=list, help_text='Les X derniers messages bruts (format LangChain JSON).')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
