# Generated by Django 4.2.15 on 2025-09-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauths', '__first__'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject_specialization', models.CharField(blank=True, help_text='Matière principale enseignée.', max_length=200)),
                ('students', models.ManyToManyField(blank=True, related_name='teachers', to='students.student')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
            bases=('userauths.user',),
        ),
    ]
