# Generated by Django 5.1.7 on 2025-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
