# Generated by Django 4.2.15 on 2025-09-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='matiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
