# Generated by Django 5.1.7 on 2025-08-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='user_id',
            new_name='user',
        ),
    ]
