# Generated by Django 5.1.7 on 2025-08-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_score_unique_together_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
