RECOMMENDATIONS = {
    "Tronc Commun": {
        "Ensembles de nombres": "https://www.youtube.com/playlist?list=PLIJfenLlfjW_Rhko9ZHIQvst7FKeEQoNo",
        "Arithmétique dans N": "https://www.youtube.com/watch?v=zlFjeTqldys&list=PLX4JM5un62hA-6CnE9WU-P0y4yyv5NPdW",
        "Calcul vectoriel": "https://www.youtube.com/watch?v=N2cM6UevpUQ&list=PLLYc1VjflHSB3B7T-984kmiu5hrc0B-r5",
        "ProjectionLa projection": "https://www.youtube.com/watch?v=GsZd1kQgB_Y&list=PLpJ48ZvxMJM31YZn2efxCxpD4G9ZUdS79",
        "Ordre dans ℝ": "https://www.youtube.com/watch?v=PSl_Cu5OeLs&list=PLLYc1VjflHSDFuyJn-SLdTo9yWVK27S__",
        "Droite dans le plan": "https://www.youtube.com/watch?v=d-rUnClmcCY&list=PLVUDmbpupCapf-dGL1hVU0grzGRrGnz1q",
        "Polynômes": "https://www.youtube.com/watch?v=dDKI3jkMjfw&list=PL024XGD7WCIHMAwUrUW5BAmHu-EiuO9nU",
        "Équations et systèmes": "https://www.youtube.com/watch?v=teZikZbqKHk&list=PLLYc1VjflHSD_pdYITsdpu7P9ihItYl-D",
        "Trigonométrie 1 (Règles du calcul trigonométrique)": "https://www.youtube.com/watch?v=tvt9cECTSH4&list=PLuj_W_ckIDLJgccE1Fzt9nbJOIGbX_Ntv",
        "Trigonométrie 2 (Identités et équations trigonométriques)": "https://www.youtube.com/watch?v=iXdSMiuPPb8&list=PLLYc1VjflHSCTNQ9mTqWNAGfm-04JRbE4",
        "Généralités sur les fonctions": "https://www.youtube.com/watch?v=3UATeEoIyuw&list=PLJ99nvBc0N-lczXjMGRoVYcajYYQd5NeT",
        "Transformations": "https://www.youtube.com/watch?v=4hACSwA1cn4&list=PLVUDmbpupCaoE3tQlqACo974XeL2r3eRJ",
        "Produit scalaire": "https://www.youtube.com/watch?v=nmjXcSc3dVg&list=PLX4JM5un62hAy0y2sr5NXisCP5k_mD_v4",
        "Géométrie dans l'espace": "https://www.youtube.com/watch?v=6hjlLk99Vvs&list=PLLYc1VjflHSAGANcAtk9QfFoVdl3yjZXi",
        "Statistiques": "https://www.youtube.com/watch?v=yTtbC1velyk"
    },
    "Premier Bac": {
        "Logique mathématique": "https://www.youtube.com/watch?v=qYniDwFnI1c&list=PLn3XTgvZWCizWCCmr1qGvp2latwJXqJej",
        "Ensembles et applications": "https://www.youtube.com/watch?v=JVyr2ZsfOnk&list=PLhtIEyVuroV0lmh2tmWNQ8M9t9c8n0jrt",
        "Généralités sur les fonctions": "https://www.youtube.com/watch?v=CSLp-wYArlE&list=PLJ99nvBc0N-n-aFiYnm2onm96oaCqRK6K",
        "barycentre dans le plan": "https://www.youtube.com/watch?v=4mX2Dc8LBLI&list=PLX4JM5un62hBhgfG6z8LwrI61qPzVRRjy",
        "produit scalaire dans le plan": "https://www.youtube.com/watch?v=W9i6Jlzuydk&list=PL0Kwtl4gdC_UTo353iFq8gFeMsfX8v58X",
        "Calcul trigonométrique": "https://www.youtube.com/watch?v=9CJrhefj7VM&list=PLX4JM5un62hBGxkd8OkgALTXK1UZqQ_xC",
        "suites numériques": "https://www.youtube.com/watch?v=f-okOBwvGWk&list=PLJ99nvBc0N-nFQh3vRcF4DA_9rudFbFBc",
        "Limites d’une fonction": "https://www.youtube.com/watch?v=ZYq6cBBSwa4&list=PLJ99nvBc0N-nVgSVdKzfz2oaf3VBZYI1K",
        "rotation dans le plan": "https://www.youtube.com/watch?v=huMV-mixKz8",
        "Dérivation": "https://www.youtube.com/watch?v=t6QJ7E5_ubE&list=PLgOzo-YcXOhBhA_CvkvowjY1qDO9Z0dcO",
        "Étude des fonctions": "https://www.youtube.com/watch?v=T02FJWLWvgQ&list=PLX4JM5un62hArVQl15KsMUUrQFUWnpZLa" ,
        "Vecteurs de l’espace": "https://www.youtube.com/watch?v=SCDTHjKyuSo&list=PLUfJOEwIb2c45haqHMQia8ct7D1E4wQ1y",
        "Géométrie dans l’espace": "https://www.youtube.com/watch?v=loNWY2kktnA&list=PLX4JM5un62hC6eL55XJ41E6jZNzcgGkNm",
        "Dénombrement": "https://www.youtube.com/watch?v=yODTn0TfAak&list=PLM8_G-VemRDFm2WkSSopIBJA-IHzj872-",
        "produit scalaire dans l'espace": "https://www.youtube.com/watch?v=QeOoSKyL_dw&list=PL_ZtK1TB2InrsTa3NZQH4i6TIJ3mSz1l0",
        "Arithmétique dans Z": "https://www.youtube.com/watch?v=BVvaflLfjCU&list=PLgOzo-YcXOhA_Sq_c5WVPFdaZOxwtDRhq",
        "produit vectoriel": "https://www.youtube.com/watch?v=2NxriGOFpsA&list=PLhwheJMLOsDBSkxQTXYf0JsjNAZxoe8SG",
    },
    "Terminale": {
        "Limites et continuité": "https://www.youtube.com/watch?v=XcLTzql_v9g&list=PLWDP1k6hCnoQkQ6ILBkiGh20L0-zK8Hz7",
        "Dérivation et étude des fonctions": "https://www.youtube.com/watch?v=T02FJWLWvgQ&list=PLX4JM5un62hArVQl15KsMUUrQFUWnpZLa",
        "Suites numériques": "https://www.youtube.com/watch?v=pA2XEI1Uv_s&list=PLPMCOIL54o6Wf82b8EGrOCdlXstx16WX2",
        "Fonctions primitives": "https://www.youtube.com/watch?v=MLVMYPY_lFE&list=PLJ99nvBc0N-kbh9lCREW0aJ06762fFhyF",
        "Fonctions logarithmiques": "https://www.youtube.com/watch?v=axAZHCBbHPk&list=PLJ99nvBc0N-lD1eLWECLmy-uZ8on-oVc2",
        "Nombres complexes": "https://www.youtube.com/watch?v=lBDkhzI-bIQ&list=PLJ99nvBc0N-m_UqZH_LJK5d6KXS54nf5k",
        "Fonctions exponentielles": "https://www.youtube.com/watch?v=BeiZrSiUS_w&list=PLJ99nvBc0N-mtWhmFWeal3uvLnHbxPow5",
        "Calcul intégral": "https://www.youtube.com/watch?v=zm8Dy4fbtFA&list=PLJ99nvBc0N-kFTiqTRTwYf3jEPqtYYdVz",
        "Équations différentielles": "https://www.youtube.com/watch?v=LX8PxR-ScfM&list=PLdz4lhk1rRmNsBJMBti9DQBNcjP7hdGpZ",
        "Géométrie dans l’espace": "https://www.youtube.com/watch?v=FqTYa6NONwY&list=PLX4JM5un62hBhgv-49WulGlHiYSsBVoKI",
        "Dénombrement et probabilités": "https://www.youtube.com/watch?v=6_Rt-P_Mtec&list=PLPMCOIL54o6UJUJ42QnD1hRQx0ar-kp93"
    }
}