# Generated by Django 5.2.4 on 2025-07-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_remove_user_created_at_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
