# Generated by Django 5.2.4 on 2025-07-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('manager', 'Manager'), ('hr', 'Human Resources'), ('head_department', 'Head Department'), ('collaborator', 'Collaborator')], default='collaborator', max_length=50),
        ),
    ]
