# Generated by Django 5.2.4 on 2025-07-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
