# Generated by Django 5.2.4 on 2025-07-23 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 23, 15, 5, 37, 390010, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
