# Generated by Django 5.1.7 on 2025-07-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
