# Generated by Django 5.1.7 on 2025-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='notification_frequency',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='phone',
        ),
        migrations.AddField(
            model_name='parent',
            name='engagement_level',
            field=models.CharField(blank=True, default='standard', max_length=100),
        ),
    ]
