# Generated by Django 5.1.7 on 2025-08-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
