# Generated by Django 5.1.7 on 2025-08-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userscore_topic'),
        ('quiz', '0002_question_explanation_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='quiz.topic'),
        ),
    ]
