# Generated by Django 5.1.7 on 2025-08-04 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userscore_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userscore',
            unique_together={('user',)},
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='topic',
        ),
    ]
