# Generated by Django 4.2.15 on 2025-08-15 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_recommendation'),
        ('profiles', '0004_alter_userscore_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='quiz.topic'),
            preserve_default=False,
        ),
    ]
