# Generated by Django 4.2.15 on 2025-08-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_topic_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='topic',
        ),
    ]
